# Generated by Django 2.0.5 on 2018-07-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
